### PR TITLE
VCR: renamed 'company' concept to 'organization', fix marshalling

### LINKED ISSUE #141: VCR: NutsOrganizationCredential contains incorrect credentialSubject
`Organization` is marshaled with a capital `O`;

```json
{
  "context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://nuts.nl/credentials/v1"
  ],
  "credentialSubject": {
    "Organization": {
      "city": "Franeker",
      "name": "Because We Care B.V."
    },
    "id": "did:nuts:Cu998wwZy2Q9qq1oVc2cKs1Ev5GmrrmDg4vJC42G3fnJ"
  },
  "id": "did:nuts:Cu998wwZy2Q9qq1oVc2cKs1Ev5GmrrmDg4vJC42G3fnJ#d044295f-3871-41f3-a099-08fbda29b705",
  "issuanceDate": "2021-03-12T15:45:43.774039013Z",
  "issuer": "did:nuts:Cu998wwZy2Q9qq1oVc2cKs1Ev5GmrrmDg4vJC42G3fnJ",
  "proof": {
    "created": "2021-03-12T15:45:43.774039013Z",
    "jws": "eyJhbGciOiJFUzI1NiIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..1aIfkBzwF2eQeFMeZU2wVRCxB0vzM0CveWEOtSH9e79fSB5oYdlZV9Pg9Nj5ds8RCwhQDXsJ9fmybH_lhjvzfw",
    "proofPurpose": "assertionMethod",
    "type": "JsonWebSignature2020",
    "verificationMethod": "did:nuts:Cu998wwZy2Q9qq1oVc2cKs1Ev5GmrrmDg4vJC42G3fnJ#PXuBU62zMv4qJGnaZuKn7ZGGZQwR5TofixswI3wOaAI"
  },
  "type": [
    "VerifiableCredential",
    "NutsOrganizationCredential",
    "VerifiableCredential"
  ]
}
```

@woutslakhorst

### PR DESCRIPTION
**Pull request by reinkrul**
Closes #141

### CODE REVIEW

**Review by woutslakhorst — CHANGES_REQUESTED** [review]
The template was deliberately different so the tests did not use the same template as a real one. Maybe `company` for the tests can be changed to `example`?

File: vcr/vcr_test.go [hunk 1]
```diff
@@ -106,7 +106,7 @@ func TestVCR_Search(t *testing.T) {
 	if !assert.NoError(t, err) {
 		return
 	}
-	q.AddClause(concept.Eq("company.name", "Because we care BV"))
+	q.AddClause(concept.Eq("organization.name", "Because we care BV"))
```
Comment (woutslakhorst) [inline vcr/vcr_test.go:109]: Shouldn't this be human.eyeColour?

**Review by woutslakhorst — CHANGES_REQUESTED** [review]

File: vcr/vcr_test.go (hunk 1 above)
Comment (reinkrul) [reply vcr/vcr_test.go:109]: Test doesn't care, apparently...

I figured this is a bug (or a feature?): when there's no (matching?) clauses it appears all entries match?

Comment (woutslakhorst) [reply vcr/vcr_test.go]: wrong setup of test I guess. This is also why your UI returns all matches without query. Since the type of credential is in the index. It then uses a partial index to find all.

**Review by woutslakhorst — APPROVED** [review]
