### PR TITLE
VCR: Untrusted only lists active issuers

### LINKED ISSUE #1065: VCR: untrusted list broken for deactivated DIDs
vcr.Untrusted just lists all credential issuers that are not in the trusted list. These DIDs may actually already be deactivated or have a deactivated controller. Resolving those DIDs will fail.

Credentials for a deactivated DID can't be used anymore: https://nuts-foundation.gitbook.io/drafts/rfc/rfc011-verifiable-credential#3.5-active-issuer

So the list must also be resolved first, any DID that's not resolvable needs to be removed.

Backport to V2

### PR DESCRIPTION
**Pull request by gerardsn**
fixes #1065

I'm not sure about the various error cases. Some extra attention for that would be appreciated.

### CODE REVIEW

File: vcr/vcr_test.go [hunk 1]
```diff
@@ -347,44 +347,56 @@ func TestVcr_Untrusted(t *testing.T) {
...
+	})
+	t.Run("Untrusted - no active controller", func(t *testing.T) {
+		confirmUntrustedStatus(t, func(issuer ssi.URI) ([]ssi.URI, error) {
+			mockDocResolver.EXPECT().Resolve(did.MustParseDIDURL(testCredential.Issuer.String()), nil).Return(nil, nil, types.ErrNoActiveController)
+			return instance.Untrusted(issuer)
+		}, 0)
+	})
+}
+func confirmUntrustedStatus(t *testing.T, fn func(issuer ssi.URI) ([]ssi.URI, error), numUntrusted int) {
+	t.Run("ok - untrusted", func(t *testing.T) {
```
Comment (woutslakhorst) [inline vcr/vcr_test.go:375]: I would remove this nested test run.

File: vcr/vcr_test.go [hunk 2]
```diff
@@ -347,44 +347,56 @@ func TestVcr_Untrusted(t *testing.T) {
...
+}
 
-			t.Run("ok - trusted", func(t *testing.T) {
-				instance.Trust(ssi.MustParseURI("NutsOrganizationCredential"), testCredential.Issuer)
-				defer func() {
-					instance.Untrust(ssi.MustParseURI("NutsOrganizationCredential"), testCredential.Issuer)
-				}()
-				trusted, err := fn(ssi.MustParseURI("NutsOrganizationCredential"))
+func confirmTrustedStatus(t *testing.T, trustManager TrustManager, issuer ssi.URI, fn func(issuer ssi.URI) ([]ssi.URI, error), numTrusted int) {
+	t.Run("ok - trusted", func(t *testing.T) {
```
Comment (woutslakhorst) [inline vcr/vcr_test.go:387]: I would remove this nested test run.

**Review by woutslakhorst — CHANGES_REQUESTED** [review]

**Review by woutslakhorst — APPROVED** [review]
