### PR TITLE
Fix/2402/retry events synchronously at startup

### LINKED ISSUE #2402: Failed events are retried asynchronous at startup
When having hundreds of events this causes DB timeouts because those events can't be handled asynchronously at that scale. At startup they should be handled synchronously.

### PR DESCRIPTION
**Pull request by woutslakhorst**
fixes #2402 

the call to retry is replaced with `notifyNow` for each event that failed in the past. The events are tried one by one. All events that still failed are then scheduled in the retry loop.

This will reduce the number of errors on startup due to DB lock errors. Events that still fail due to other causes still fail and will still be rescheduled.

### CODE REVIEW

File: network/dag/notifier.go [hunk 1]
```diff
@@ -239,16 +239,31 @@ func (p *notifier) Run() error {
...
+	failedAtStartup := make([]Event, 0)
+	err := p.db.ReadShelf(p.ctx, p.shelfName(), func(reader stoabs.Reader) error {
 		return reader.Iterate(func(k stoabs.Key, v []byte) error {
 			event := Event{}
 			_ = json.Unmarshal(v, &event)
 
-			p.retry(event)
+			if err := p.notifyNow(event); err != nil {
+				failedAtStartup = append(failedAtStartup, event)
+			}
```
Comment (gerardsn) [inline network/dag/notifier.go:251]: this changes some logic. Events with `Event.Retries >= maxRetries` should not be retried.

**Review by gerardsn — CHANGES_REQUESTED** [review]
This adds a requirement on the startup order of the modules. Network MUST be started after all modules that subscribe to the notifier for this change to work (which it currently does).

The DB issue arrises when there are many events with the same number of `Event.Retries` since these all get the same initial delay in `p.retry`. This could also be solved by adding some jitter to the initial delay.

File: network/dag/notifier.go (hunk 1 above)
Comment (woutslakhorst) [reply network/dag/notifier.go:251]: > this changes some logic. Events with `Event.Retries >= maxRetries` should not be retried.

That is already the case @ startup

Comment (gerardsn) [reply network/dag/notifier.go]: I think the checks are in the wrong order? It still retries when the maxRetries is reached. (might also fix the broken test)

Comment (gerardsn) [reply network/dag/notifier.go]: hmm... I see what you're saying. Everything is retried at startup after the initial delay, which is 2^100 sec == never for events that hit an `EventFatal` error. `p.retry` is basically collecting go routines that sleep forever...?

Comment (gerardsn) [reply network/dag/notifier.go]: time.Second^100 overflows and results in `0s` in go, so it retries immediately. I'd say that this is a different bug? 

Also, `retry.Attempts(maxRetries-uint(initialCount)),` in `p.retry` result in infinite retries when `initialCount== maxRetries`

mehhh

Comment (woutslakhorst) [reply network/dag/notifier.go]: Added Jitter as well. Hopefully the test isn't going to random fail

**Review by gerardsn — APPROVED** [review]
Seems reasonable. Just a nasty race condition left according to the tests.

**Comment by woutslakhorst** [comment]
@gerardsn reduced max retry to 20 to prevent overflow. Set jitter to equal initialDelay to prevent race conditions in test. Jitter and initialDelay were both 1s... Also helps in test where sometimes initialDelay is 1ns

File: network/dag/notifier.go [hunk 2]
```diff
@@ -330,21 +347,24 @@ func (p *notifier) Notify(event Event) {
...
 	}
 
 	go func(ctx context.Context) {
-		// also an initial delay
-		time.Sleep(delay)
 		err := retry.Do(func() error {
 			return p.notifyNow(event)
 		},
-			retry.Attempts(maxRetries-uint(initialCount)),
+			retry.Attempts(attempts),
```
Comment (gerardsn) [inline network/dag/notifier.go:363]: `attempts==0` means infinite Attempts

Comment (woutslakhorst) [reply network/dag/notifier.go:363]: anything <0 and >max will just return the retry.
