### PR TITLE
did:x509: x5c claim is DER base64, not PEM

### LINKED ISSUE #3596: did:x509 JWT x5c field processing incorrectly assumes PEM, should be base64 DER instead

### PR DESCRIPTION
**Pull request by reinkrul**
Fixes #3596

Also deduplicates test code

### CODE REVIEW

File: vdr/didx509/x509_utils_test.go [hunk 1]
```diff
@@ -20,258 +20,26 @@ package didx509
...
-		return nil, nil, err
-	}
-	// PEM encode the certificate (this is a standard TLS encoding)
-	b := pem.Block{Type: "CERTIFICATE", Bytes: certDER}
-	certPEM = pem.EncodeToMemory(&b)
-	return cert, certPEM, err
-}
-
 func TestFindOtherNameValue(t *testing.T) {
 	t.Parallel()
```
Comment (woutslakhorst) [inline vdr/didx509/x509_utils_test.go:38]: Not from you, but this is not needed.

**Review by woutslakhorst — APPROVED** [review]

File: vdr/didx509/x509_utils_test.go (hunk 1 above)
Comment (reinkrul) [reply vdr/didx509/x509_utils_test.go:38]: I'll remove it
