### PR TITLE
fix holder credential autocorrect credentialsubject.id

### LINKED ISSUE #3696: VP builder should set correct credentialSubject.id on self-asserted credentials
for subjects with multiple DIDs an access token request can result in:
```
{ "detail": "invalid_request - not all VCs have the same credentialSubject.id", "status": 400, "title": "RequestServiceAccessToken failed" }
```

to reproduce with scope `test:HuisartsVVTInzage` that requires a `X509Credential` issued to a `did:web` and the `EmployeeCredential` (for a subject that also has a `did:nuts`):
```
POST https://example.com/internal/auth/v2/{serviceID}/request-service-access-token
Content-Type: application/json

{
  "authorization_server": "https://example.com/oauth2/{serviceID}",
  "scope": "test:HuisartsVVTInzage",
  "credentials": [
    {
      "@context": [
        "https://www.w3.org/2018/credentials/v1",
        "https://nuts.nl/credentials/v1"
      ],
      "type": [
        "VerifiableCredential",
        "EmployeeCredential"
      ],
      "credentialSubject": {
        "name": "John Doe",
        "roleName": "Janitor",
        "identifier": "123456"
      }
    }
  ],
  "token_type": "Bearer"
}
```

Manually setting the `credentialSubject.id` to the `did:web` fixes the problem.

I expect the node to set the correct subject on the `EmployeeCredential`

### PR DESCRIPTION
**Pull request by woutslakhorst**
fixes #3696 

backport to V6.0

### CODE REVIEW

**Review by reinkrul — APPROVED** [review]

File: vcr/credential/util.go [hunk 1]
```diff
@@ -136,6 +136,7 @@ func AutoCorrectSelfAttestedCredential(credential vc.VerifiableCredential, reque
 		}
 		if _, ok := credentialSubject[0]["id"]; !ok {
 			credentialSubject[0]["id"] = requester.String()
+			credential.CredentialSubject = make([]interface{}, 1)
```
Comment (gerardsn) [inline vcr/credential/util.go:139]: this is only a partial fix. If `didmetnods`config is `[web,nuts]` and the `credentialSubject.id` is already set by the user to the `did:nuts` address, it will still create a wallet with multiple DIDs as subject

**Review by gerardsn — DISMISSED** [review]

File: vcr/credential/util.go (hunk 1 above)
Comment (woutslakhorst) [reply vcr/credential/util.go:139]: that was the idea: 3717
