### PR TITLE
did:x509: improved ca-fingerprint validation

### LINKED ISSUE #3587: did:x509 issuer and resolver assume the root CA as ca-fingerprint
Which is wrong: in practice, this will be PKIOverheid Private Service Root CA, meaning _any_ intermediate CA certificate is accepted. This would allow more intermediate CAs than CIBG UZI (through KPN) to issue certificates that can used to create `UziServerCertificateCredential`.

The did:x509 spec states that the ca-fingerprint property can be of any root or intermediate CA. It's then up to the verifier (in our case through PEX) to restrict this to the accepted trust anchors

Meaning:
- The uzi-x509-issuer tool should take the direct issuer of the UZI server certificate (deepest intermediate CA), since this (probably) what use cases/Bolts want to configure in their PEX PDs
- The DID resolver in the Nuts node should take any ca-fingerprint to validate the cert chain, instead of hardcoded assume it's the root CA's ca-fingerprint.

### PR DESCRIPTION
**Pull request by reinkrul**
Fixes #3587 for the parsing in the Nuts node. Issuer tool will still have to be fixed.

It was actually already supported, just the field name was incorrect. But, it was missing a validation check; ca-fingerprint is not allowed to reference the leaf certificate (intermediate CA or root CA only).

### CODE REVIEW

**Comment by gerardsn** [comment]
`make install-tools && make gen-mocks`

File: vdr/didx509/resolver.go [hunk 1]
```diff
@@ -107,14 +108,17 @@ func (r Resolver) Resolve(id did.DID, metadata *resolver.ResolveMetadata) (*did.
...
+	caFingerprintCert, err := findCertificateByHash(chain, ref.CAFingerprint, ref.Method)
 	if err != nil {
 		return nil, nil, err
 	}
 	validationCert, err := findValidationCertificate(metadata, chain)
 	if err != nil {
 		return nil, nil, err
 	}
+	if bytes.Equal(caFingerprintCert.Raw, validationCert.Raw) {
+		return nil, nil, fmt.Errorf("did:509 ca-fingerprint refers to leaf certificate, must be either root or intermediate CA certificate")
```
Comment (gerardsn) [inline vdr/didx509/resolver.go:120]:
```suggestion
		return nil, nil, fmt.Errorf("did:x509 ca-fingerprint refers to leaf certificate, must be either root or intermediate CA certificate")
```

File: vdr/didx509/resolver.go [hunk 2]
```diff
@@ -107,14 +108,17 @@ func (r Resolver) Resolve(id did.DID, metadata *resolver.ResolveMetadata) (*did.
...
+	}
```
Comment (gerardsn) [inline vdr/didx509/resolver.go:121]: Is this requirement true for all did:x509 resolving, or specifically for our use-case?
If so, I think this means the policy file is incorrect: Can we detect that once somewhere else instead of during every resolving action?
(I can't find in our documentation which did:x509 spec we are using so I couldn't look it up)

**Review by gerardsn — CHANGES_REQUESTED** [review]

File: vdr/didx509/resolver.go [hunk 3]
```diff
@@ -78,9 +79,9 @@ type X509DidPolicy struct {
 
 // X509DidReference represents a reference for an X.509 Decentralized Identifier (DID) including method, root certificate, and policies.
 type X509DidReference struct {
-	Method      HashAlgorithm
-	RootCertRef string
-	Policies    []X509DidPolicy
+	Method        HashAlgorithm
+	CAFingerprint string
```
Comment (gerardsn) [inline vdr/didx509/resolver.go:83]: update godoc

File: vdr/didx509/resolver.go (hunk 2 above)
Comment (reinkrul) [reply vdr/didx509/resolver.go:121]: https://trustoverip.github.io/tswg-did-x509-method-specification/#identifier-syntax states:

> ca-fingerprint is chain[i].fingerprint[ca-fingerprint-alg] with i > 0, that is, either an intermediate or root CA certificate.

Although it's kinda cryptic, given x5c is sorted leaf-to-root, I think what they mean (twice) is that it shouldn't be the leaf, but a CA cert.

**Review by gerardsn — APPROVED** [review]
