### PR TITLE
fix correct backup store initiation

### LINKED ISSUE #2448: Creating backup stores is extremely slow
After removing the bbolt backup stores in the VCR it takes 2 hours for the node to rebuild them and start the node.
Logs below are from a basic node on the stable network (see timestamps)
```
2023-08-29 14:58:36 time="2023-08-29T12:58:36Z" level=info msg="Setting up FileSystem backend for storage of private key material. Discouraged for production use unless backups and encryption is properly set up. Consider using the Hashicorp Vault backend." module=Crypto
2023-08-29 14:58:36 time="2023-08-29T12:58:36Z" level=info msg="Missing store for shelf, creating from index" module=Storage storeShelf=revocations
2023-08-29 15:09:12 time="2023-08-29T13:09:12Z" level=info msg="Missing store for shelf, creating from index" module=Storage storeShelf=credentials
2023-08-29 16:56:42 time="2023-08-29T14:56:42Z" level=warning msg="Deprecated: use `tls.certfile` instead of `network.certfile`"
```

probably related to #2323 and friends

### PR DESCRIPTION
**Pull request by woutslakhorst**
fixes #2448 

The set that is written in a single transaction is now correctly reset after a transaction.

### CODE REVIEW

**Review by gerardsn — APPROVED** [review]

**Comment by gerardsn** [comment]
Moving declaration of `set` (L130) down a bit may prevent it getting confused with the set in `writeDocuments` in the future

**Comment by woutslakhorst** [comment]
have to add something to release notes

File: storage/leia.go [hunk 1]
```diff
@@ -136,15 +136,16 @@ func (k *kvBackedLeiaStore) handleRestore(config LeiaBackupConfiguration) error
 					return err
 				}
 			}
-			set = make([]refDoc, 0)
 			return nil
 		})
 	}
```
Comment (reinkrul) [inline storage/leia.go:142]: For pro move, initialize `var set []refDoc` here instead of at line 130 to make sure you don't accidentally use the wrong variable in `writeDocuments`. Now the func shadows the outer `set` var.

File: storage/leia.go [hunk 2]
```diff
@@ -136,15 +136,16 @@ func (k *kvBackedLeiaStore) handleRestore(config LeiaBackupConfiguration) error
...
 
 	err := collection.Iterate(query, func(ref leia.Reference, value []byte) error {
 		set = append(set, refDoc{ref: ref, doc: value})
 		if len(set) >= limit {
-			return writeDocuments(set)
+			err := writeDocuments(set)
+			set = make([]refDoc, 0)
```
Comment (reinkrul) [inline storage/leia.go:147]: should you allocate a slice with cap 100? (micro optimization though)

**Review by reinkrul — CHANGES_REQUESTED** [review]

File: storage/leia.go (hunk 2 above)
Comment (woutslakhorst) [reply storage/leia.go:147]: than `len` would already say 100?

**Review by reinkrul — APPROVED** [review]
