### PR TITLE
pass ResolveMetadata for resolving VC issuer

### LINKED ISSUE #743: Issueing credentials from a DID that has a deactivated controller succeeds
But validating fails,

when issueing, the VCR does not pass any metadata to the DIDDoc.Resolve. This will bypass resolving the controllers.
It shoud also resolveControllers. This can be fixed by passing a metadata with resolve time set to now.

### PR DESCRIPTION
**Pull request by woutslakhorst**
fixes #743 

Passing resolveMetadata enables the controller active check.

### CODE REVIEW

File: vcr/vcr.go [hunk 1]
```diff
@@ -305,8 +305,9 @@ func (c *vcr) Issue(template vc.VerifiableCredential) (*vc.VerifiableCredential,
 	if err != nil {
 		return nil, fmt.Errorf("failed to parse issuer: %w", err)
 	}
-	// find did document/metadata for originating TXs
-	document, meta, err := c.docResolver.Resolve(*issuer, nil)
+	// find did document/metadata for originating TXs. ResolveMetadata is required to also check the validity of the issuer's controller.
+	now := timeFunc()
```
Comment (reinkrul) [inline vcr/vcr.go:309]: is this equal to the issuance time of the VC?

Comment (woutslakhorst) [reply vcr/vcr.go:309]: give or take a few milliseconds. We could add issuance time to the VC builder to make sure they are the same at nanosecond level?

**Review by reinkrul — APPROVED** [review]

File: vcr/vcr.go (hunk 1 above)
Comment (reinkrul) [reply vcr/vcr.go:309]: Would be nice (in a sense, more pure), but probably doesn't really matter much in practice.
