### PR TITLE
Iss232 fix service in token

### LINKED ISSUE #232: auth: service scope not set in bearer token
This prevents the custodian from checking the correct aud

### PR DESCRIPTION
**Pull request by woutslakhorst**
Fixes #232

### CODE REVIEW

File: auth/services/oauth/oauth.go [hunk 1]
```diff
@@ -291,6 +291,8 @@ func claimsFromRequest(request services.CreateJwtBearerTokenRequest, audience st
 	result[jwt.IssuerKey] = request.Actor
 	result[jwt.NotBeforeKey] = 0
 	result[jwt.SubjectKey] = request.Custodian
+	result[jwt.SubjectKey] = request.Custodian
```
Comment (reinkrul) [inline auth/services/oauth/oauth.go:294]: duplicate?

**Review by reinkrul — CHANGES_REQUESTED** [review]

File: auth/services/oauth/oauth.go (hunk 1 above)
Comment (woutslakhorst) [reply auth/services/oauth/oauth.go:294]: incorrect merge I guess

**Review by reinkrul — APPROVED** [review]
