### PR TITLE
Provide CLI commands for querying node status and diagnostics

### LINKED ISSUE #38: 'diagnostics' CLI command doesn't work
Should return the diagnostics of the remote server

### PR DESCRIPTION
**Pull request by reinkrul**
Fixes #38

### CODE REVIEW

File: core/status/cmd.go [hunk 1]
```diff
@@ -0,0 +1,61 @@
...
+	cmd := &cobra.Command{
+		Use:   "status",
+		Short: "Shows the status of the Nuts Node.",
+		RunE: func(cmd *cobra.Command, args []string) error {
+			config := core.NewClientConfig()
+			if err := config.Load(cmd.PersistentFlags()); err != nil {
+				return err
+			}
+			var targetURL string
+			if verbose {
```
Comment (woutslakhorst) [inline core/status/cmd.go:42]: a bit overkill since a status call will only return 200 OK and should never have a return body of any significance

**Review by woutslakhorst — CHANGES_REQUESTED** [review]
I think returning diagnostics is enough. Status doesn't add anything,.

File: core/status/cmd.go (hunk 1 above)
Comment (reinkrul) [reply core/status/cmd.go:42]: I agree

**Review by woutslakhorst — APPROVED** [review]
