### PR TITLE
disable did:web root e2e-test

### LINKED ISSUE #3299: broken test e2e-tests/oauth-flow/openid4vp/didweb-root.sh
support for root dids (or subjects) was (partially) removed in #3269. The e2e is still passing though. Reconsider changes in mentioned PR or fix this test

### PR DESCRIPTION
**Pull request by woutslakhorst**
fixes #3299 

re-enabling root did:web DIDs will not be part of the 6.0 release. It can be added in a minor, then the test can be fixed properly.

### CODE REVIEW

File: e2e-tests/oauth-flow/openid4vp/run-test.sh [hunk 1]
```diff
@@ -1,4 +1,5 @@
 #!/usr/bin/env bash
 set -e
 ./do-test.sh didweb-user
-./do-test.sh didweb-root
\ No newline at end of file
+# skip test, root did:web is not supported and test is broken
```
Comment (gerardsn) [inline e2e-tests/oauth-flow/openid4vp/run-test.sh:4]: reference issue for info on what is broken

**Review by gerardsn — APPROVED** [review]
