### PR TITLE
fix panic when VCs do not have a custom type

### LINKED ISSUE #1512: Change in validation allows for VCs without type which causes a panic
`in vcr/store.go#71` there's a line that says: "// validation has made sure there's exactly one!".

I think validation has changed and therefore the code now reaches this point and causes a panic!

### PR DESCRIPTION
**Pull request by woutslakhorst**
fixes #1512

less strict validation on VC type introduced a panic. Extra painful is that it was only used for logging.

### CODE REVIEW

File: vcr/store.go [hunk 1]
```diff
@@ -65,8 +65,11 @@ func (c *vcr) StoreCredential(credential vc.VerifiableCredential, validAt *time.
 }
 
 func (c *vcr) writeCredential(subject vc.VerifiableCredential) error {
-	// validation has made sure there's exactly one!
-	vcType := credential.ExtractTypes(subject)[0]
+	vcType := "VerifiableCredential"
+	customTypes := credential.ExtractTypes(subject)
```
Comment (gerardsn) [inline vcr/store.go:69]: subject.Type is guaranteed to contain "VerifiableCredential", and at most 1 other type.

**Review by gerardsn — APPROVED** [review]
