### PR TITLE
return 404 for missing token sessionID

### LINKED ISSUE #3130: Incorrect return status on unknown auth session when requesting access token
```
node-right-1   | time="2024-05-22T08:42:19Z" level=info msg="HTTP request" method=GET module=http remote_ip=172.90.10.8 status=500 uri=/internal/auth/v2/accesstoken/pl5hGvDnlhmh5Iqevfeo-CgKjCqd95Lm-UFsupOGCQw
```

1st call returns access token, 2nd call should return 404

### PR DESCRIPTION
**Pull request by gerardsn**
closes #3130

### CODE REVIEW

**Review by woutslakhorst — APPROVED** [review]

File: auth/api/iam/api.go [hunk 1]
```diff
@@ -231,6 +231,9 @@ func (r Wrapper) RetrieveAccessToken(_ context.Context, request RetrieveAccessTo
 	var token TokenResponse
 	err := r.accessTokenClientStore().Get(request.SessionID, &token)
 	if err != nil {
+		if errors.Is(err, storage.ErrNotFound) {
+			return nil, core.NotFoundError("session not found")
```
Comment (reinkrul) [inline auth/api/iam/api.go:235]: shouldn't this be an oauth2 error?

**Review by reinkrul — CHANGES_REQUESTED** [review]

File: auth/api/iam/api.go (hunk 1 above)
Comment (woutslakhorst) [reply auth/api/iam/api.go:235]: it's an internal API

**Review by reinkrul — APPROVED** [review]
