### PR TITLE
fix overriding VAULT_TOKEN with empty default

### LINKED ISSUE #1464: VAULT_TOKEN env variable not usable due to empty overwrite from default config.
```
ERRO[0000] unable to connect to Vault: unable to retrieve token status: Error making API request.

URL: GET http://192.168.10.141:8200/v1/auth/token/lookup-self
Code: 403. Errors:

* permission denied
```

crypto/storage/vault.go#94 in `configureVaultClient` does not check for empty token

Also backport to V4

### PR DESCRIPTION
**Pull request by woutslakhorst**
fixes #1464

### CODE REVIEW

File: crypto/storage/vault.go [hunk 1]
```diff
@@ -91,7 +91,11 @@ func configureVaultClient(cfg VaultConfig) (*vault.Client, error) {
 	if err != nil {
 		return nil, fmt.Errorf("unable to initialize Vault client: %w", err)
 	}
-	client.SetToken(cfg.Token)
+	// The Redis client will automatically use the env var VAULT_TOKEN
```
Comment (gerardsn) [inline crypto/storage/vault.go:94]: Should this be:
```suggestion
	// The Vault client will automatically use the env var VAULT_TOKEN
```

**Review by gerardsn — APPROVED** [review]

**Review by stevenvegt — APPROVED** [review]
