### PR TITLE
Fix crypto fs storage

### LINKED ISSUE #1704: NTS-008: Crypto FS storage file creation permissions
Files are created with `666`, should be `600`.
Files can overwrite files with same name (very small change since the filename is the hash of the public key).

### PR DESCRIPTION
**Pull request by stevenvegt**
Fixes #1704 
File permissions to 0600 and don't create when already exists.

### CODE REVIEW

**Review by reinkrul — COMMENTED** [review]
What permission should the directory (createdirs) have?

**Comment by stevenvegt** [comment]
> What permission should the directory (createdirs) have?
ROS advises 0700. That is part of NTS-006.

File: crypto/storage/fs.go [hunk 1]
```diff
@@ -95,7 +95,7 @@ func (fsc *fileSystemBackend) GetPrivateKey(kid string) (crypto.Signer, error) {
 // SavePrivateKey saves the private key for the given key to disk. Files are postfixed with '_private.pem'. Keys are stored in pem format.
 func (fsc *fileSystemBackend) SavePrivateKey(kid string, key crypto.PrivateKey) error {
 	filenamePath := fsc.getEntryPath(kid, privateKeyEntry)
-	outFile, err := os.Create(filenamePath)
+	outFile, err := os.OpenFile(filenamePath, os.O_WRONLY|os.O_CREATE|os.O_EXCL, os.FileMode(0600))
```
Comment (reinkrul) [inline crypto/storage/fs.go:98]: this function could be simpler using `os.WriteFile()` which doesn't involve handling file handles

**Review by reinkrul — APPROVED** [review]

File: crypto/storage/fs.go (hunk 1 above)
Comment (stevenvegt) [reply crypto/storage/fs.go:98]: Almost, but that one allows overwriting existing files. Here we include the `os.O_EXCL` flag to prevent that.
