### PR TITLE
Remove temporary irma schema dirs at startup

### LINKED ISSUE #1656: Startup fails when irma scheme dir is corrupt
Sometimes the node exits during startup with the following error:
`Error: no scheme file found`

This comes from
https://github.com/privacybydesign/irmago/blob/0778649dd4b4161e7f473192b68df84b85bdd853/internal/common/common.go#L386-L397

In my understanding this can happen when a scheme is partially downloaded.

We should probably try to catch this, remove all contents of the directory and try again.

### PR DESCRIPTION
**Pull request by stevenvegt**
fixes #1656

### CODE REVIEW

File: auth/services/irma/irmaconfig.go [hunk 1]
```diff
@@ -47,8 +48,27 @@ func GetIrmaConfig(validatorConfig ValidatorConfig) (irmaConfig *irma.Configurat
...
 	}
 
+	// This fixes an IRMA bug https://github.com/privacybydesign/irmago/issues/139
+	// It removes any temporary "tempscheme123" directories, leftover from a previous unfinished schema update.
+	dirs, err := filepath.Glob(filepath.Join(validatorConfig.IrmaConfigPath, "tempscheme*"))
+	if err != nil {
+		return
+	}
+	for _, dir := range dirs {
+		log.Logger().Infof("removing leftover temporary IRMA scheme dir: %s", dir)
```
Comment (reinkrul) [inline auth/services/irma/irmaconfig.go:58]:
```suggestion
		log.Logger().Infof("Removing leftover temporary IRMA scheme dir: %s", dir)
```

File: auth/services/irma/irmaconfig.go [hunk 2]
```diff
@@ -47,8 +48,27 @@ func GetIrmaConfig(validatorConfig ValidatorConfig) (irmaConfig *irma.Configurat
 		return
 	}
 
+	// This fixes an IRMA bug https://github.com/privacybydesign/irmago/issues/139
+	// It removes any temporary "tempscheme123" directories, leftover from a previous unfinished schema update.
+	dirs, err := filepath.Glob(filepath.Join(validatorConfig.IrmaConfigPath, "tempscheme*"))
+	if err != nil {
+		return
```
Comment (reinkrul) [inline auth/services/irma/irmaconfig.go:55]: is the `err` actually returned, since it's shadowed on line 53?

File: auth/services/irma/irmaconfig.go [hunk 3]
```diff
@@ -47,8 +48,27 @@ func GetIrmaConfig(validatorConfig ValidatorConfig) (irmaConfig *irma.Configurat
...
+	}
+	for _, dir := range dirs {
+		log.Logger().Infof("removing leftover temporary IRMA scheme dir: %s", dir)
+		if err := os.RemoveAll(dir); err != nil {
+			log.Logger().Warnf("unable to remove dir: %s", err)
```
Comment (reinkrul) [inline auth/services/irma/irmaconfig.go:60]: I think this is an error to be returned? Otherwise, the node can't start anyways?

File: auth/services/irma/irmaconfig.go [hunk 4]
```diff
@@ -47,8 +48,27 @@ func GetIrmaConfig(validatorConfig ValidatorConfig) (irmaConfig *irma.Configurat
...
+		}
+	}
+
 	log.Logger().Debug("Loading IRMA schemas...")
-	return irmaConfig, irmaConfig.ParseFolder()
+	if err = irmaConfig.ParseFolder(); err != nil {
+		log.Logger().Errorf("Could not parse the IRMA schemas: %s", err)
+		log.Logger().Info("You can try emptying the irma schema directory to solve this.")
+		return nil, err
+
```
Comment (reinkrul) [inline auth/services/irma/irmaconfig.go:69]:
```suggestion
```

File: auth/services/irma/irmaconfig.go [hunk 5]
```diff
@@ -47,8 +48,27 @@ func GetIrmaConfig(validatorConfig ValidatorConfig) (irmaConfig *irma.Configurat
...
+		if err := os.RemoveAll(dir); err != nil {
+			log.Logger().Warnf("unable to remove dir: %s", err)
+		}
+	}
+
 	log.Logger().Debug("Loading IRMA schemas...")
-	return irmaConfig, irmaConfig.ParseFolder()
+	if err = irmaConfig.ParseFolder(); err != nil {
+		log.Logger().Errorf("Could not parse the IRMA schemas: %s", err)
+		log.Logger().Info("You can try emptying the irma schema directory to solve this.")
```
Comment (reinkrul) [inline auth/services/irma/irmaconfig.go:67]: just keep it part of the error message

File: auth/services/irma/irmaconfig.go [hunk 6]
```diff
@@ -47,8 +48,27 @@ func GetIrmaConfig(validatorConfig ValidatorConfig) (irmaConfig *irma.Configurat
...
+		log.Logger().Infof("removing leftover temporary IRMA scheme dir: %s", dir)
+		if err := os.RemoveAll(dir); err != nil {
+			log.Logger().Warnf("unable to remove dir: %s", err)
+		}
+	}
+
 	log.Logger().Debug("Loading IRMA schemas...")
-	return irmaConfig, irmaConfig.ParseFolder()
+	if err = irmaConfig.ParseFolder(); err != nil {
+		log.Logger().Errorf("Could not parse the IRMA schemas: %s", err)
```
Comment (reinkrul) [inline auth/services/irma/irmaconfig.go:66]:
```suggestion
		log.Logger().WithError(err).Error("Could not parse the IRMA schemas")
```

**Review by reinkrul — CHANGES_REQUESTED** [review]

File: auth/services/irma/irmaconfig.go (hunk 3 above)
Comment (stevenvegt) [reply auth/services/irma/irmaconfig.go:60]: So, perhaps just ignore it?

Comment (reinkrul) [reply auth/services/irma/irmaconfig.go:60]: Return the error, I'd say

Comment (stevenvegt) [reply auth/services/irma/irmaconfig.go]: I think this is bugfix code, if it fails, just try to continue, perhaps the failure is not critical, the actual execution of the lines down below will tell.

File: auth/services/irma/irmaconfig.go [hunk 7]
```diff
@@ -47,8 +48,24 @@ func GetIrmaConfig(validatorConfig ValidatorConfig) (irmaConfig *irma.Configurat
...
+	for _, dir := range dirs {
+		log.Logger().Infof("removing leftover temporary IRMA scheme dir: %s", dir)
+		// ignore any errors, it will fail below
+		_ = os.RemoveAll(dir)
+	}
+
 	log.Logger().Debug("Loading IRMA schemas...")
-	return irmaConfig, irmaConfig.ParseFolder()
+	if err = irmaConfig.ParseFolder(); err != nil {
+		log.Logger().WithError(err).Error("could not parse the IRMA schemas, try emptying the irma directory and restart the node.")
```
Comment (reinkrul) [inline auth/services/irma/irmaconfig.go:65]:
```suggestion
		log.Logger().WithError(err).Error("Could not parse the IRMA schemas, try emptying the IRMA directory and restart the node.")
```

**Review by reinkrul — APPROVED** [review]
